apiVersion: v1
kind: Service
metadata:
  name: opentelemetry-collector
  namespace: observability
  labels:
    app.kubernetes.io/name: opentelemetry-collector
spec:
  selector:
    app.kubernetes.io/name: opentelemetry-collector
  ports:
    - name: otlp-grpc
      port: 4317
      targetPort: otlp-grpc
    - name: otlp-http
      port: 4318
      targetPort: otlp-http
    - name: prometheus
      port: 9464
      targetPort: prometheus
