apiVersion: v1
kind: LimitRange
metadata:
  name: observastack-limits
  namespace: observastack
  labels:
    app.kubernetes.io/part-of: observastack
    app.kubernetes.io/managed-by: gitops
spec:
  limits:
    - type: Container
      defaultRequest:
        cpu: 100m
        memory: 128Mi
      default:
        cpu: 500m
        memory: 512Mi
      max:
        cpu: "4"
        memory: 8Gi
---
apiVersion: v1
kind: LimitRange
metadata:
  name: observability-limits
  namespace: observability
  labels:
    app.kubernetes.io/part-of: observastack
    app.kubernetes.io/managed-by: gitops
spec:
  limits:
    - type: Container
      defaultRequest:
        cpu: 250m
        memory: 256Mi
      default:
        cpu: "1"
        memory: 1Gi
      max:
        cpu: "8"
        memory: 16Gi
---
apiVersion: v1
kind: LimitRange
metadata:
  name: platform-system-limits
  namespace: platform-system
  labels:
    app.kubernetes.io/part-of: observastack
    app.kubernetes.io/managed-by: gitops
spec:
  limits:
    - type: Container
      defaultRequest:
        cpu: 100m
        memory: 128Mi
      default:
        cpu: 500m
        memory: 512Mi
      max:
        cpu: "4"
        memory: 8Gi
