apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cm
  namespace: argocd
  labels:
    app.kubernetes.io/part-of: argocd
data:
  resource.respectRBAC: "strict"
  resource.sensitive.mask.annotations: "kubectl.kubernetes.io/last-applied-configuration"
  resource.customLabels: "app.kubernetes.io/name,app.kubernetes.io/part-of,app.kubernetes.io/component"
