apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-resource-exclusions
  namespace: argocd
  labels:
    app.kubernetes.io/part-of: argocd
data:
  resource.exclusions: |
    - apiGroups:
      - events.k8s.io
      kinds:
      - Event
      clusters:
      - "*"
