apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespaces/observastack.yaml
  - namespaces/observability.yaml
  - namespaces/platform-system.yaml
  - config/priority-classes.yaml

  - resource-policies/resource-quotas.yaml
  - resource-policies/limit-ranges.yaml
  
  - network-policies/default-deny.yaml
  - network-policies/dns.yaml
  - network-policies/namespace-traffic.yaml