apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: observastack-production
  namespace: argocd
spec:
  description: ObservaStack production workloads
  sourceRepos:
    - https://github.com/Emmy-github-webdev/observastack.git
  destinations:
    - server: https://kubernetes.default.svc
      namespace: observastack
  clusterResourceWhitelist: []
  namespaceResourceWhitelist:
    - group: ""
      kind: ConfigMap
    - group: ""
      kind: Secret
    - group: ""
      kind: Service
    - group: apps
      kind: Deployment
    - group: apps
      kind: StatefulSet
    - group: autoscaling
      kind: HorizontalPodAutoscaler
    - group: policy
      kind: PodDisruptionBudget
    - group: networking.k8s.io
      kind: Ingress
    - group: networking.k8s.io
      kind: NetworkPolicy
  syncWindows:
    - kind: deny
      schedule: "0 0 * * *"
      duration: 24h
      applications:
        - "*"
      manualSync: true
